### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by adadychanka** [KyzAlexander/TestingInJavaScript#1]
Объявленный args нигде не используется.

https://github.com/KyzAlexander/TestingInJavaScript/blob/4a74f95a5ac30af25d73580ca2ffbc0aeb8a9dc1/src/test/functionsForTesting.js#L1

---

Невалидная проверка. Если функция отработает неправильно, то тест всё равно пройдёт.
https://github.com/KyzAlexander/TestingInJavaScript/blob/4a74f95a5ac30af25d73580ca2ffbc0aeb8a9dc1/src/test/test.test.js#L28

---

Тоже самое

https://github.com/KyzAlexander/TestingInJavaScript/blob/4a74f95a5ac30af25d73580ca2ffbc0aeb8a9dc1/src/test/test.test.js#L82

**Comment by KyzAlexander** [comment]
(...args) показываю что сюда могут прокидываться параметры 
но там же на выходе должна быть пустая строка, вот я и проверяю чтобы она была. Или лучше вместо пустой строки надо false написать ?
